{% set name = "geomodels" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3ca0a607892317ba306a0e2d0a9d0bc6a856771c0c683cb5db3eddfec083d762

build:
  skip: True  # [py<310]
  entry_points:
    - geomodels-cli = geomodels.cli:main
  script_env:
    - GEOMODELS_IGNORE_BUNDLED_LIBS=TRUE
    - GEOMODELS_GEOGRAPHICLIB_NAME=GeographicLib-i  # [win]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
  host:
    - python
    - cython
    - geographiclib-cpp >=2.0
    - numpy
    - pip
    - setuptools
  run:
    - argcomplete
    - geographiclib-cpp >=2.0
    - numpy
    - python
    - tqdm

test:
  imports:
    - geomodels
    - geomodels.tests
  requires:
    - pip
    - pytest
  commands:
    - pip check
    - geomodels-cli --help
    - geomodels-cli install-data -d data recommended
    - python -m geomodels info
    - env GEOGRAPHICLIB_DATA=./data python -m pytest --pyargs geomodels

about:
  home: https://github.com/avalentino/geomodels
  summary: 'Python package for Earth data models management'
  description: |
    GeoModels provides tools for the management of Earth models like
    geoids, gravity models, and magnetic field models.
    It also provides some utility function to download and install
    support data to that are necessary for Earth models computation.
    It is basically a Cython_ wrapper for part of the the GeographicLib
    C++ library.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://geomodels.readthedocs.io
  dev_url: https://github.com/avalentino/geomodels

extra:
  recipe-maintainers:
    - avalentino
